"""swipe history for application

Revision ID: 092d8e6d1d00
Revises: 8259d3bbb00d
Create Date: 2025-06-05 08:09:01.765816

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '092d8e6d1d00'
down_revision: Union[str, None] = '8259d3bbb00d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # First create the enum type
    op.execute("CREATE TYPE swipeaction AS ENUM ('LIKE', 'DISLIKE')")
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('applications', 
                 sa.Column('action', 
                          postgresql.ENUM('LIKE', 'DISLIKE', name='swipeaction'), 
                          nullable=False,
                          server_default='LIKE'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('applications', 'action')
    # ### end Alembic commands ###
    # Then drop the enum type
    op.execute("DROP TYPE swipeaction")
