"""add chat initial table

Revision ID: 5823db900d28
Revises: fc9e8cef0a47
Create Date: 2025-06-05 15:55:33.369155

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '5823db900d28'
down_revision: Union[str, None] = 'fc9e8cef0a47'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('applications', 'action',
               existing_type=postgresql.ENUM('LIKE', 'DISLIKE', name='swipeaction'),
               server_default=None,
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('applications', 'action',
               existing_type=postgresql.ENUM('LIKE', 'DISLIKE', name='swipeaction'),
               server_default=sa.text("'LIKE'::swipeaction"),
               existing_nullable=False)
    # ### end Alembic commands ###
