"""Add JobReport model and update relationships

Revision ID: 82158e9e710f
Revises: 8db43f8e0922
Create Date: 2025-06-04 10:11:19.919800

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '82158e9e710f'
down_revision: Union[str, None] = '8db43f8e0922'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('job_reports',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('job_id', sa.UUID(), nullable=False),
    sa.Column('reporter_id', sa.Integer(), nullable=True),
    sa.Column('reviewed_by', sa.Integer(), nullable=True),
    sa.Column('reason', sa.String(length=500), nullable=False),
    sa.Column('reported_at', sa.DateTime(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'REVIEWED', 'DISMISSED', 'ACTIONED', name='reportstatus'), nullable=False),
    sa.Column('job_deleted', sa.Boolean(), server_default='false', nullable=True),
    sa.Column('reporter_deleted', sa.Boolean(), server_default='false', nullable=True),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['reporter_id'], ['user.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['reviewed_by'], ['user.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_job_reports_id'), 'job_reports', ['id'], unique=False)
    op.create_index(op.f('ix_job_reports_job_id'), 'job_reports', ['job_id'], unique=False)
    op.add_column('jobs', sa.Column('report_count', sa.Integer(), server_default='0', nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('jobs', 'report_count')
    op.drop_index(op.f('ix_job_reports_job_id'), table_name='job_reports')
    op.drop_index(op.f('ix_job_reports_id'), table_name='job_reports')
    op.drop_table('job_reports')
    # ### end Alembic commands ###
