"""remove unnecessary fields from job_report table

Revision ID: 8259d3bbb00d
Revises: 82158e9e710f
Create Date: 2025-06-04 12:17:12.598025

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8259d3bbb00d'
down_revision: Union[str, None] = '82158e9e710f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('job_reports', 'job_deleted')
    op.drop_column('job_reports', 'reporter_deleted')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('job_reports', sa.Column('reporter_deleted', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=True))
    op.add_column('job_reports', sa.Column('job_deleted', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
