"""withdraw application from applications

Revision ID: fc9e8cef0a47
Revises: 85e137d6fd38
Create Date: 2025-06-05 09:42:25.160630

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'fc9e8cef0a47'
down_revision: Union[str, None] = '85e137d6fd38'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # op.alter_column('applications', 'action',
    #            existing_type=postgresql.ENUM('LIKE', 'DISLIKE', name='swipeaction'),
    #            server_default=None,
    #            existing_nullable=False)
    op.execute("ALTER TYPE applicationstatus ADD VALUE 'WITHDRAWN'")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # op.alter_column('applications', 'action',
    #            existing_type=postgresql.ENUM('LIKE', 'DISLIKE', name='swipeaction'),
    #            server_default=sa.text("'LIKE'::swipeaction"),
    #            existing_nullable=False)
    pass
    # ### end Alembic commands ###
